### PR TITLE
Fix incorrect Faraday error being asserted against.

### PR DESCRIPTION
**Pull request by damian**
Addressed some formatting inconsistencies.

Added a top level `uploadcare-api` file as this wasn't automatically
being loaded by Ruby's `require`.

Added a .rspec file to output some colour on the CLI.

### CODE REVIEW

**Comment by dmitry-mukhin** [comment]
thanks!

could it be that Faraday has changed the error raised and it was correct earlier?

**Comment by damian** [comment]
Quite possibly though I haven't been able to find any documentation to verify this.

The best I've been able to come up with is [this commit](https://github.com/lostisland/faraday/commit/4ac193943b93ce20cc01a5736aa3f6022174f6c8) which looks like it introduces its own Faraday SSL error class rather than falling through to a ConnectionFailed error.

**Comment by dmitry-mukhin** [comment]
Could you fix dependencies to working versions?

**Comment by damian** [comment]
Done.

**Comment by dmitry-mukhin** [comment]
thanks!

**Pull request merged**
