### PR TITLE
Fix uploading from url

### PR DESCRIPTION
**Pull request by prognostikos**
Retry the upload from url status check for 30 seconds by default.

### CODE REVIEW

**Comment by dmitry-mukhin** [comment]
Looks good!
API hadn't changed, the lib was relying on uploads vie URL being super fast.

Reference implementation can be found in [pyuploadcare](https://github.com/uploadcare/pyuploadcare/blob/master/pyuploadcare/api_resources.py#L278-L378)

I would recommend to change behavior to timeout instead of retry attempts.

**Comment by prognostikos** [comment]
@dmitry-mukhin I'll use timeout and add the parameters as default arguments as in pyuploadcare. 

Unfortunately the test failures seem to be unrelated to my PR and I won't have a chance to fix them in the near future :(.

**Comment by dmitry-mukhin** [comment]
that's ok.

**Comment by prognostikos** [comment]
@dmitry-mukhin I've tested this locally and it's working for me

**Comment by dmitry-mukhin** [comment]
Thanks!

**Pull request merged**
